# Generated by Django 5.2.6 on 2025-09-11 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_email', models.EmailField(max_length=100)),
                ('customer_contact', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'customer_t',
            },
        ),
    ]
