# Generated by Django 5.2.6 on 2025-09-11 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=100)),
                ('vehicle_make', models.CharField(max_length=50)),
                ('vehicle_model', models.CharField(max_length=50)),
                ('vehicle_color', models.CharField(max_length=30)),
                ('vehicle_year', models.IntegerField()),
                ('vehicle_price', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                'db_table': 'product_t',
            },
        ),
    ]
