# Generated by Django 5.2.6 on 2025-09-11 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='vehicle_make',
        ),
        migrations.RemoveField(
            model_name='product',
            name='vehicle_year',
        ),
        migrations.AddField(
            model_name='product',
            name='vehicle_maker',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='vehicle_model_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='vehicle_color',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='vehicle_model',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='vehicle_price',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=14, null=True),
        ),
    ]
