# Generated by Django 5.2.6 on 2025-09-11 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shipper',
            fields=[
                ('shipper_id', models.AutoField(primary_key=True, serialize=False)),
                ('shipper_name', models.CharField(max_length=100)),
                ('shipper_contact_details', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'shipper_t',
            },
        ),
    ]
