# Generated by Django 5.2.6 on 2025-09-11 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipper',
            name='shipper_contact_details',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='shipper',
            name='shipper_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='shipper',
            name='shipper_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
