# Generated by Django 5.2.6 on 2025-09-11 04:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
        ('product', '0001_initial'),
        ('shipper', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('vehicle_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('order_date', models.DateField()),
                ('ship_date', models.DateField()),
                ('customer_feedback', models.CharField(blank=True, max_length=20, null=True)),
                ('quarter_number', models.IntegerField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
                ('shipper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shipper.shipper')),
            ],
            options={
                'db_table': 'order_t',
            },
        ),
    ]
